language: java

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.m2

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script:
  - mvn clean install
